### ISSUE TITLE
Remove In from the end of this line

### ISSUE THREAD

**Issue by jwgarrett** [pkic/pkimm#32]
https://github.com/pkic/pkimm/blob/830223b9afa3bbcd464fc0cb8f46b6af4d85e04a/model/_index.md?plain=1#L71C1-L71C33

Howdy,

I wanted to let you know of a typo that I found. Awesome work by the way!

**Comment by 3keyroman** [comment]
Thanks @jwgarrett , fixed by https://github.com/pkic/pkimm/commit/0aa269078dcfe3df1a955ec49a0ceea798b8501d.
